### ISSUE TITLE
BEM issue

### ISSUE THREAD

**Issue by rudnitskih** [dimavasilenko/uber-eats-react#3]
Correct className - `header__logo-wrapper`

![image](https://user-images.githubusercontent.com/8848858/60031037-aea37500-96ac-
11e9-85ae-f46459d9dcc3.png)

**Comment by scandy5** [comment]
https://github.com/dimavasilenko/uber-eats-react/blob/69ada1dfe93a9f1da3aaf8e73dd4cc76d1fd1573/src/components/header/header.jsx#L10
